apiVersion: v1
kind: Service
metadata:
  namespace: akka-test
  name: akka-test-frontend
  labels:
    app: akka-test-frontend
spec:
  clusterIP: None
  ports:
  - port: 5054
  selector:
    app: akka-test-frontend

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: akka-test
  name: akka-test-frontend
  labels:
    app: akka-test-frontend
spec:
  serviceName: akka-test-frontend
  replicas: 1
  selector:
    matchLabels:
      app: akka-test-frontend
  template:
    metadata: 
      labels:
        app: akka-test-frontend
    spec:
      containers:
      - name: akka-test-frontend
        image: xili10dockerregistry.azurecr.io/akka-test:poolv4.1
        env:
        - name: ACTORSYSTEM
          value: ClusterSystem
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).akka-test-frontend"
        - name: CLUSTER_PORT
          value: "5054"
        - name: CLUSTER_SEEDS
          value: akka.tcp://$(ACTORSYSTEM)@lighthouse-0.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-1.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-2.lighthouse:4053
        - name: TOTALREQUEST
          value: "1000000"
        livenessProbe:
          tcpSocket:
            port: 5054
        ports:
        - containerPort: 5054
          protocol: TCP
        command: ["dotnet", "Samples.Cluster.RoundRobinCore.dll", "frontend"]