---
apiVersion: v1
kind: Namespace
metadata:
  name: akka-test
  labels:
    name: akka-test

---
apiVersion: v1
kind: Service
metadata:
  name: akka-test-backend
  namespace: akka-test
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 2551
      targetPort: 2551

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: akka-test-backend
  namespace: akka-test
spec:
   replicas: 1
   selector:
      matchLabels:
        app: backend
   template:
      metadata:
        labels:
          app: backend
      spec:
          containers:
            - name: akka-test-backend
              image: xili10dockerregistry.azurecr.io/akka-test:v2.3
              command: ["dotnet", "Samples.Cluster.RoundRobinCore.dll", "backend"]